const PREFIX = "student";
export const GET_STUDENT_FULLFILLED = `${PREFIX}/GET_STUDENT_FULLFILLED`;
export const SELECT_STUDENT = `${PREFIX}/SELECT_STUDENT`;
export const UPDATE_STUDENT = `${PREFIX}/UPDATE_STUDENT`;
export const SEARCH_VALUE = `${PREFIX}/SEARCH_VALUE`;
export const GET_STUDENT_PENDING = `${PREFIX}/GET_STUDENT_PENDING`;
export const GET_STUDENT_REJECTED = `${PREFIX}/GET_STUDENT_REJECTED`;
